package com.mobilabtestassignment.rebekka.backend.model

import javax.persistence.Entity
import javax.persistence.GeneratedValue
import javax.persistence.GenerationType
import javax.persistence.Id

/**
 * ItemModel is the model for the items in this application
 * Every item consists of:
 * Auto generated by the database Int id
 * listId shows which list this item belongs to
 * value shows what is the String title or content what was inserted when creating this item
 * checkedState show whether the checkbox on this item is checked (true) or unchecked (false)
 */
@Entity
data class ItemModel (@Id
                      @GeneratedValue(strategy = GenerationType.AUTO)
                      val id: Int = 0,
                      val listId: Int,
                      val value: String,
                      val checkedState: Boolean){


}
