package com.mobilabtestassignment.rebekka.backend.model

/**
 * ListModel is the model for the lists in this application
 * Every list consists of:
 * Auto generated by the database Int id
 * name shows what is the String title or content what was inserted when creating this list
 */
data class ListModel(val id: Int, val name: String)
